Update to  CardboardEditor.cs.
Here is patch for "error CS0117: `UnityEditor.PlayerSettings' does not contain a definition for 'target IOS Graphics'" in CardboardEditor.cs. `UnityEditor.PlayerSettings' does not contain a definition for 'target IOS Graphics'" in CardboardEditor.cs.

Here are list of SDK's and software's I am using :
1.0 Unity 4.6.2 ( Target Platform : Android )
 2.0 Cardboard SDK for Unity v0.5